Repository linkloud/linkloud.io, pull requests merged in 2023-07, with the labels that each got.

#98 feat:404page Redirect
  backend/src/main/java/io/linkloud/api/domain/Controller.java
  backend/src/main/java/io/linkloud/api/domain/ErrorPageController.java
Labels: ✨ enhancement, BE

#101 Feat/discord webhook
  backend/src/main/java/io/linkloud/api/domain/ErrorPageController.java
  backend/src/main/java/io/linkloud/api/domain/discord/TestController.java
  backend/src/main/java/io/linkloud/api/domain/discord/entity/DiscordWebhook.java
  backend/src/main/java/io/linkloud/api/domain/discord/service/DiscordWebhookService.java
  backend/src/main/java/io/linkloud/api/global/advice/ExceptionAdvice.java
  backend/src/main/java/io/linkloud/api/global/exception/ExceptionCode/LogicExceptionCode.java
  backend/src/test/resources/application.yml
Labels: ✨ enhancement, BE

#102 Refactor/member role and logout
  backend/src/main/java/io/linkloud/api/domain/member/service/MemberService.java
  backend/src/main/java/io/linkloud/api/domain/member/service/SchedulerService.java
  backend/src/main/java/io/linkloud/api/global/security/SecurityConfig.java
  backend/src/test/java/io/linkloud/api/domain/member/api/AuthControllerTest.java
Labels: 📁 docs, BE, 🔧 refactor

#108 fix: 태그를 엔터키로 등록시 마지막 문자가 남던 현상
  client/src/features/articles/hooks/useArticleReg.ts
  client/src/features/articles/pages/Reg.tsx
Labels: fix

#110 chore: head title명 한글로 변경 #109
  client/index.html
Labels: ✨ enhancement

#112 feat: 모바일 네비게이션
  client/src/assets/svg/home-fill.svg
  client/src/assets/svg/home.svg
  client/src/assets/svg/inbox-fill.svg
  client/src/assets/svg/index.ts
  client/src/assets/svg/user-fill.svg
  client/src/components/Layout/DefaultLayout.tsx
  client/src/components/Navigation/MobileNavigation.tsx
  client/src/components/Navigation/hooks/useMobileNavigation.ts
  client/src/components/Navigation/index.ts
  client/src/features/articles/pages/Reg.tsx
Labels: ✨ enhancement

#114 feat: Head 컴포넌트
  client/index.html
  client/src/components/Head/Head.tsx
  client/src/components/Head/index.tsx
  client/src/features/articles/pages/Search.tsx
Labels: ✨ enhancement

#106 Feature/search article
  backend/src/main/java/io/linkloud/api/domain/article/api/ArticleController.java
  backend/src/main/java/io/linkloud/api/domain/article/dto/ArticleUpdateDto.java
  backend/src/main/java/io/linkloud/api/domain/article/service/ArticleService.java
  backend/src/test/java/io/linkloud/api/domain/article/service/ArticleServiceTest.java
Labels: BE, 🔧 refactor

#115 Feat/my articles
  backend/src/main/docs/asciidoc/index.adoc
  backend/src/main/java/io/linkloud/api/domain/article/repository/ArticleRepository.java
  backend/src/main/java/io/linkloud/api/domain/member/api/MemberController.java
  backend/src/main/java/io/linkloud/api/domain/member/dto/MyArticlesResponseDto.java
  backend/src/main/java/io/linkloud/api/domain/member/model/Member.java
  backend/src/main/java/io/linkloud/api/domain/member/service/MemberService.java
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
Labels: 📁 docs, ✨ enhancement, BE

#116 Refactor/member me response
  backend/src/main/java/io/linkloud/api/domain/member/dto/MemberLoginResponse.java
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
Labels: 📁 docs, BE, 🔧 refactor

#117 Feat/my article status
  backend/src/main/docs/asciidoc/index.adoc
  backend/src/main/java/io/linkloud/api/domain/article/dto/ArticleStatusRequest.java
  backend/src/main/java/io/linkloud/api/domain/article/dto/ArticleStatusResponse.java
  backend/src/main/java/io/linkloud/api/domain/article/model/Article.java
  backend/src/main/java/io/linkloud/api/domain/article/model/ArticleStatus.java
  backend/src/main/java/io/linkloud/api/domain/member/api/MemberController.java
  backend/src/main/java/io/linkloud/api/domain/member/dto/MyArticlesResponseDto.java
  backend/src/main/java/io/linkloud/api/domain/member/model/Member.java
  backend/src/main/java/io/linkloud/api/domain/member/service/MemberService.java
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
Labels: 📁 docs, ✨ enhancement, BE

#121 feat: 내 링크 클릭시 로그인 모달 나타나게 수정
  client/src/assets/svg/home-fill.svg
  client/src/assets/svg/home.svg
  client/src/assets/svg/inbox-fill.svg
  client/src/assets/svg/inbox.svg
  client/src/assets/svg/plus.svg
  client/src/components/Header/DefaultHeader.tsx
  client/src/components/Header/hooks/useHeader.ts
  client/src/components/Navigation/MobileNavigation.tsx
  client/src/components/Navigation/hooks/useMobileNavigation.ts
  client/src/features/articles/hooks/useArticleReg.ts
  client/src/features/misc/pages/Landing.tsx
  client/src/features/misc/pages/NotFound.tsx
  client/src/features/tags/pages/Tags.tsx
  client/src/routes/constants/index.ts
  client/src/routes/privateRoutes.tsx
  client/src/routes/publicRoutes.tsx
Labels: ✨ feature

#122 feat: seo #109
  client/index.html
  client/src/features/articles/pages/Reg.tsx
  client/src/features/articles/pages/Search.tsx
  client/src/features/misc/pages/Landing.tsx
  client/src/features/misc/pages/NotFound.tsx
  client/src/features/tags/pages/Tags.tsx
Labels: ✨ feature

#120 Feature/member article
  backend/src/main/java/io/linkloud/api/domain/article/dto/MyArticlesResponseDto.java
  backend/src/main/java/io/linkloud/api/domain/article/model/Article.java
  backend/src/main/java/io/linkloud/api/domain/article/repository/ArticleRepositoryCustom.java
  backend/src/main/java/io/linkloud/api/domain/article/repository/ArticleRepositoryImpl.java
  backend/src/main/java/io/linkloud/api/domain/member/api/MemberController.java
  backend/src/main/java/io/linkloud/api/domain/member/service/MemberService.java
  backend/src/main/java/io/linkloud/api/domain/tag/Service/TagService.java
  backend/src/main/java/io/linkloud/api/domain/tag/repository/TagRepositoryImpl.java
  backend/src/main/java/io/linkloud/api/global/Utils/QueryDslUtils.java
  backend/src/main/java/io/linkloud/api/global/config/QueryDslConfig.java
  backend/src/main/java/io/linkloud/api/global/config/WebConfig.java
  backend/src/main/java/io/linkloud/api/global/converter/StringToArticleSortByConverter.java
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
  backend/src/test/java/io/linkloud/api/domain/tag/repository/TagRepositoryTest.java
Labels: ✨ feature, BE, 🔧 refactor

#125 feat: 태그 등록방식 변경
  client/src/components/Input/InputText.tsx
  client/src/components/Layout/DefaultLayout.tsx
  client/src/features/articles/hooks/useArticleReg.ts
  client/src/features/articles/pages/Reg.tsx
  client/src/features/articles/pages/Search.tsx
  client/src/features/tags/components/TagItem.tsx
Labels: ✨ feature, FE

#127 docs: 내 게시글 조회 문서화 수정
  backend/src/main/docs/asciidoc/index.adoc
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
Labels: 📁 docs, BE

#130 Feature/member article
  backend/src/main/java/io/linkloud/api/domain/article/dto/ArticleResponseDto.java
  backend/src/main/java/io/linkloud/api/domain/article/dto/MyArticlesResponseDto.java
  backend/src/main/java/io/linkloud/api/domain/article/repository/ArticleRepositoryImpl.java
  backend/src/main/java/io/linkloud/api/domain/member/api/MemberController.java
  backend/src/test/java/io/linkloud/api/domain/article/service/ArticleServiceTest.java
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
Labels: BE, 🔧 refactor

#131 Feat/get member tags
  backend/src/main/docs/asciidoc/index.adoc
  backend/src/main/java/io/linkloud/api/domain/member/api/MemberController.java
  backend/src/main/java/io/linkloud/api/domain/member/repository/MemberRepository.java
  backend/src/main/java/io/linkloud/api/domain/member/repository/MemberRepositoryCustom.java
  backend/src/main/java/io/linkloud/api/domain/member/repository/MemberRepositoryImpl.java
  backend/src/main/java/io/linkloud/api/domain/member/service/MemberService.java
  backend/src/main/java/io/linkloud/api/domain/tag/dto/MemberTagsDto.java
  backend/src/test/java/io/linkloud/api/domain/member/api/MemberControllerTest.java
Labels: docs, feature, BE

#133 feat: url 한글 입력 허용 #132
  client/src/features/articles/hooks/useArticleReg.ts
Labels: feature, FE

#134 feat: 내 아티클 조회 & 읽음 상태 관리
  client/src/assets/css/style.css
  client/src/assets/css/util.css
  client/src/assets/svg/book-open-check.svg
  client/src/assets/svg/book-open.svg
  client/src/assets/svg/book.svg
  client/src/assets/svg/index.ts
  client/src/assets/svg/more-horizon.svg
  client/src/components/Header/DefaultHeader.tsx
  client/src/features/articles/components/LinkArticle.tsx
  client/src/features/articles/types/index.ts
  client/src/features/members/apis/index.ts
  client/src/features/members/components/MyLinkArticle.tsx
  client/src/features/members/components/MyLinkArticles.tsx
  client/src/features/members/components/MyTags.tsx
  client/src/features/members/components/ReadStatus.tsx
  client/src/features/members/hooks/index.ts
  client/src/features/members/hooks/useMyArticles.ts
  client/src/features/members/hooks/useMyTags.ts
  client/src/features/members/pages/Links.tsx
  client/src/features/members/types/index.ts
  client/src/features/misc/pages/Landing.tsx
  client/src/features/tags/components/TagItem.tsx
  client/src/routes/privateRoutes.tsx
  client/src/stores/useAuthStore.ts
Labels: feature, FE

#136 feat: 모달 중복된 컴포넌트 전역 모달관리로 해결
  client/src/components/Chip/SelectableChip.tsx
  client/src/components/Header/DefaultHeader.tsx
  client/src/components/Header/HeaderLayout.tsx
  client/src/components/Header/hooks/useHeader.ts
  client/src/components/Header/index.ts
  client/src/components/Layout/DefaultLayout.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/Modals.tsx
  client/src/components/Modal/index.ts
  client/src/components/Navigation/MobileNavigation.tsx
  client/src/components/Navigation/hooks/useMobileNavigation.ts
  client/src/stores/useAuthStore.ts
  client/src/stores/useModalStore.ts
Labels: feature, FE

#142 fix: 헤더 로그인, 사용자 프로필 새로고침 깜빡임 현상
  client/src/App.tsx
  client/src/assets/svg/index.ts
  client/src/components/Auth/AuthModal.tsx
  client/src/components/Auth/GoogleLoginButton.tsx
  client/src/components/Header/DefaultHeader.tsx
  client/src/components/Header/hooks/useHeader.ts
  client/src/components/Header/index.ts
  client/src/components/Modal/Modals.tsx
  client/src/components/Navigation/hooks/useMobileNavigation.ts
  client/src/features/members/components/MyLinkArticle.tsx
  client/src/features/members/pages/Links.tsx
  client/src/lib/axios/helper.ts
  client/src/routes/privateRoutes.tsx
  client/src/stores/useAuthStore.ts
Labels: fix
